### ISSUE TITLE
Remove LogCallbacks from core 

### ISSUE THREAD

**Issue by ratuspro** [SciencerIO/sciencer-toolkit#11]
By default, a new LogCallbacks is added to `Sciencer.iteration`.
Instead, the developer should decide whether to use it or not.

As such, the LogCallbacks must not be added by default to the iteration's callbacks.

**Comment by RicardoEPRodrigues** [comment]
I suggest moving it to the `Utils`.

**Comment by hineios** [comment]
Solved by #18
